config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :projects

  resources :policies

  resources :events

  match '/articles(/:year(/:month))' => 'articles#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'events#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/tasks/calendar(/:year(/:month))' => 'tasks#view_calendar', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  resources :tasks

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new,:create,:destroy]
  
  match "/tasks/index.js", :controller => 'tasks', :action => 'index', :format => :js
  get "users/new"

  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  
  match '/projects/new_user', :to=>'projects#new_user'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :delegations
  has_many :users, :through=>:delegations
  
  accepts_nested_attributes_for :delegations, :allow_destroy=>true #All i had to do was add allow destroy to allow a delegation to be destroyed from project edit button!
  accepts_nested_attributes_for :users, :allow_destroy=>true
  
  attr_accessible :users_attributes, :delegations_attributes, :users, :name, :project_attributes
  
  has_many :events
  accepts_nested_attributes_for :events
  attr_accessor :project_user
    
  def should_validate_user
  project_user
  end
  
  def destroy_na
    puts "**************************************!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!****************************************!!!!!!!"
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    if current_project
      @open_project = current_project.name
    end
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    cookies.permanent.signed[:open_project] = @project.id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    #@user.project_user = params[:user][:delegations_attributes].nil?
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
        cookies.permanent[:open_project] = @project.id
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    cookies.delete(:open_project)
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_cookie(project_id)
    cookies.permanent.signed[:open_project]=project_id
  end
end

app/views/projects/_delegation_fields.html.erb
<p class="fields">
  	<%=f.text_field :role%>
    <%=f.label :responsibility%>
  	<%=f.text_field :responsibility%>
  	<%=f.label :project_id%>
  	<%=f.text_field :project_id, :value=>current_project.id%><br/>
  	<%= f.hidden_field :_destroy%>
    <%= link_to_remove_fields "Remove delegation", f %>
 </p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field"><%= f.label :money %><br />
    <%= f.text_field :money %>
  </div>
  <div class="field">
    <%= f.label :funding_agency %><br />
    <%= f.text_field :funding_agency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project_user.html.erb
<h1>New project</h1>  
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--<div class="field">
  <%=f.fields_for :delegations do |builder|%>
  	<%=builder.label :role%>
  	<%=builder.text_field :role%><br/>
  	<%=builder.label :responsibility%>
  	<%=builder.text_field :responsibility%><br/>
  <%end%>
 </div>
 <div class="field">
  	<%=f.fields_for :user do |u|%>
  	<%=u.label :name%>
  	<%=u.text_field :name%>
  	<%end%>
 </div>-->
  <div class="field">
   <%=f.fields_for :users do |u|%>
  	<%=render 'user_fields', :f=>u%>
  	<%end%>
 </div>

 <div class="field">
  <%=f.fields_for :delegations do |builder|%>
  	<%=render 'delegation_fields', :f=>builder%>
  	<%= link_to_add_fields "Add delegation",f,:delegations%>
  <%end%>
 </div>
 </div>
  <div class="actions">
	<%= f.submit "Update"%>
</div>
<% end %>

app/views/projects/_projects_sidemenu.html.erb
<h3>Projects menu</h3>
<!--make openproject a function which checks for nil-->
<%if(!Project.find(cookies.signed[:open_project]).users.first.nil?)%>
<%= Project.find(cookies.signed[:open_project]).users.first.name%><br/>
<%= Project.find(cookies.signed[:open_project]).users.last.name%>

<%end%>
<%=link_to "Assign user to project",new_user_path(:project_user=>"true")%>


app/views/projects/_user_fields.html.erb
<p class="fields">
  	<%=f.label :name%>
  	<%=f.text_field :name%>
    <%= link_to_remove_fields "Remove user", f %>
 </p>

app/views/projects/edit.html.erb
<div class="grid_4 layout">
	<%= render 'projects_sidemenu'%>
</div>
<div class ="grid_12 layout" id="right_display">

<%=render 'project_user' %>	
<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<div class="grid_4 layout">
	<%= render 'projects_sidemenu'%>
</div>
<div class ="grid_12 layout box_1" id="right_display">
<h1>Listing projects <%=@open_project%></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Time</th>
    <th>Money</th>
    <th>Funding agency</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.time %></td>
    <td><%= project.money %></td>
    <td><%= project.funding_agency %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>
</div>

<div class ="grid_12 layout box_1" id="right_display">
	Bla
</div>

<div class ="grid_12 layout box_1" id="right_display">
	Ble
</div>

app/views/projects/new.html.erb
<div class="grid_4 layout">
	<%= render 'projects_sidemenu'%>
</div>
<div class ="grid_12 layout" id="right_display">
<%=render 'form'%>
<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class="grid_4 layout">
	<%= render 'projects_sidemenu'%>
</div>
<div class ="grid_12 layout" id="right_display">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Time:</b>
  <%= @project.time %>
</p>

<p>
  <b>Money:</b>
  <%= @project.money %>
</p>

<p>
  <b>Funding agency:</b>
  <%= @project.funding_agency %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</div>