config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :projects

  resources :policies

  resources :events

  match '/articles(/:year(/:month))' => 'articles#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'events#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/tasks/calendar(/:year(/:month))' => 'tasks#view_calendar', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  resources :tasks

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new,:create,:destroy]
  
  match "/tasks/index.js", :controller => 'tasks', :action => 'index', :format => :js
  get "users/new"

  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  
  match '/projects/new_user', :to=>'projects#new_user'

end

app/views/layouts/_footer.html.erb
	<footer>
			<nav>
			<ul>
				<li><%= link_to "About", about_path%></li>
				<li><%= link_to "Contact", contact_path%></li> 
				<li><%= link_to "News", "http://news.railstutorial.org/"%></li>
				<li><%= link_to "Rails tutorial", "http://railstutorial.org"%></li>
			</ul>
		</nav>
	</footer>

app/views/layouts/_header.html.erb
	<header>
	<div class="grid_16 layout">
		<div class="grid_3 alpha" >
		<%= link_to logo, root_path%>
		</div>
		<div class="grid_13 omega">
			<nav class="round" id="nav_bar">
			<ul>
				<li><%= link_to "Home", root_path%></li>
				<li><%= link_to "Projects", projects_path%></li>
				<li><%= link_to "Profile", current_user%></li>
				<li><%= link_to "Users", users_path%></li>
				<%if current_user%>
				<li><%= link_to "Settings", edit_user_path(current_user)%></li>
				<%end%>
				<li><%= link_to "Help", help_path%></li>
				<%if signed_in? %> 
				<li><%= link_to "Sign out", signout_path, :method => :delete%></li>
				<%else%>
				<li><%= link_to "Sign in", signin_path%></li>
				<%end%>
			</ul>
			</nav>
			<%if current_user%>
		       <%=render 'layouts/nav_header'%>
			<%end%>
	    </div>
	</div>
	<div class="grid_16 separation">
	</div>
</header>

app/views/layouts/_nav_header.html.erb
<div id="main_nav">
			<ul>
				<li id="overview"><%= link_to "Overview", projects_path%></li>
				<li id="phases"><%= link_to "Home", root_path%></li>
				<li id="people"><%= link_to "Users", users_path%></li>
				<li id="meetings"><%= link_to "Events", events_path%></li>
				<li id="tasks"><%= link_to "Tasks", tasks_path%></li>
				<li id="policies"><%= link_to "Policies", policies_path%></li>
				<li id="help"><%= link_to "Home", root_path%></li>
			</ul>
</div>

app/views/layouts/_stylesheets.html.erb
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= stylesheet_link_tag '960', :media => 'screen' %>
  <%= stylesheet_link_tag 'formtastic', :media => 'screen' %>
 <%= stylesheet_link_tag 'event_calendar', :media => 'screen' %>
 <%= stylesheet_link_tag 'jquery.dataTables', :media => 'screen' %>
  <%= stylesheet_link_tag 'demo_page', :media => 'screen' %>
   <%= stylesheet_link_tag 'demo_table_jui', :media => 'screen' %>
    <%= stylesheet_link_tag 'demo_table', :media => 'screen' %>
 
  <%= javascript_include_tag "application","jquery.rails.js" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", :media=>'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=title%></title>
	<%= render 'layouts/stylesheets'%>
  <%= csrf_meta_tags %>
  <!--<%= javascript_include_tag :defaults %>-->
  
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "jquery.rails.js", "event_calendar.js","http://datatables.net/download/build/jquery.dataTables.nightly.js" %>
</head>
<body class = "container_16">
    <%= render 'layouts/header'%>
    	
	<% flash.each do |key,value|%>
	
	<div class="flash <%=key%>"><%=value %></div>
	<%end%>
	
<%= yield%>
<!--<%= render 'layouts/footer'%>-->
<!--<%= debug(params) if Rails.env.development?%>-->

</body>
</html>